CC = gcc
CFLAGS = -Wall -Wextra

all: tcpserver tcpclient udpserver udpclient

tcpserver: tcpserver.c
	$(CC) $(CFLAGS) -o $@ $^

tcpclient: tcpclient.c
	$(CC) $(CFLAGS) -o $@ $^

udpserver: udpserver.c
	$(CC) $(CFLAGS) -o $@ $^

udpclient: udpclient.c
	$(CC) $(CFLAGS) -o $@ $^

clean:
	rm -f tcpserver tcpclient udpserver udpclient